version: "3"
services:
  db:
    restart: always
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "forum_db"
    ports:
      - 5432:5432
  api:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      FLASK_APP: "kite"
      FLASK_DEBUG: 1
      API_DB_HOST: "db"
      API_DB_PORT: "5432"
      API_DB_USERNAME: "admin"
      API_DB_PASSWORD: "pass"
      API_DB_NAME: "forum_db"
      FORUM_ADMIN: "fadmin"
      FORUM_ADMIN_PASS: "password"
      SPY_LOG_LOGGER: "pretty-no-meta"
    ports:
      - 5000:5000
    volumes:
      - ".:/opt:z"
